from collections import OrderedDict

fixtures_map = OrderedDict([
    ('sites', 'wagtailcore.Site'),
    ('settings', 'core.FolioBlogSettings'),
    ('collections', 'wagtailcore.Collection'),
    ('photographers', 'core.Photographer'),
    ('images', 'core.FolioImage'),
    ('tags', 'taggit.Tag'),
    ('taggeditems', 'taggit.TaggedItem'),
    ('pages', 'wagtailcore.Page'),
    ('portfolio', 'portfolio.PortFolioPage'),
    ('basicpages', 'core.BasicPage'),
    ('blogcategories', 'blog.BlogCategory'),
    ('blogindex', 'blog.BlogIndexPage'),
    ('blogpages', 'blog.BlogPage'),
    ('blogtags', 'blog.BlogTag'),
    ('blogpagetags', 'blog.BlogPageTag'),
    ('blogpromote', 'blog.BlogPromote'),
    ('blogpromotelink', 'blog.BlogPromoteLink'),
    ('searchindex', 'search.SearchIndexPage'),
    ('videoindex', 'video.VideoIndexPage'),
    ('videocategories', 'video.VideoCategory'),
    ('videotags', 'video.VideoTag'),
    ('videopagetags', 'video.VideoPageTag'),
    ('videopages', 'video.VideoPage'),
    ('videopromote', 'video.VideoPromote'),
    ('videopromotelink', 'video.VideoPromoteLink'),
    ('basicpagerelatedlinks', 'core.BasicPageRelatedLink'),
    ('blogpagerelatedlinks', 'blog.BlogPageRelatedLink'),
    ('videopagerelatedlinks', 'video.VideoPageRelatedLink'),
    ('homepage', 'home.HomePage'),
    ('gallerypage', 'gallery.GalleryPage'),
    ('menu', 'core.Menu'),
    ('menulink', 'core.MenuLink'),
])
