services:

  nginx:
    image: nginx:1.25
    container_name: folioblog_nginx
    restart: always
    environment:
      NGINX_HOST: ${FOLIOBLOG_NGINX_HOST}
      NGINX_APP_PORT: ${FOLIOBLOG_APP_PORT:-8000}
      NGINX_SSL_CERT: ${FOLIOBLOG_NGINX_SSL_CERT}
      NGINX_SSL_KEY: ${FOLIOBLOG_NGINX_SSL_KEY}
    ports:
      - ${FOLIOBLOG_NGINX_PORT:-80}:80
      - ${FOLIOBLOG_NGINX_PORT_SSL:-443}:443
    networks:
      default:
        aliases:
          - folio.local
          - demo.folio.local
          - blog.folio.local
    volumes:
      - ./docker/prod/nginx/templates:/etc/nginx/templates:ro
      - ./docker/prod/nginx/ssl/certs:/etc/nginx/ssl:ro
      - folioblog_media:/media:ro
      - folioblog_static:/static:ro

  app:
    image: ychab/wagtail_folioblog:latest
    container_name: folioblog_app
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      nginx:
        condition: service_started
    build:
      context: .
      dockerfile: ./docker/prod/Dockerfile
    environment:
      FOLIOBLOG_POSTGRES_PASSWORD_FILE: /run/secrets/pg_passwd
      FOLIOBLOG_REDIS_PASSWORD_FILE: /run/secrets/redis_passwd
      FOLIOBLOG_SECRET_KEY_FILE: /run/secrets/secret_key
      FOLIOBLOG_EMAIL_HOST_PASSWORD_FILE: /run/secrets/email_passwd
    env_file:
      - ./docker/prod/.env.prod
      - ./.env.prod
    ports:
      - ${FOLIOBLOG_APP_PORT:-8000}:8000
    volumes:
      - folioblog_media:/app/media
      - folioblog_static:/app/static
    secrets:
      - pg_passwd
      - redis_passwd
      - secret_key
      - email_passwd
    healthcheck:
      test: curl --fail http://127.0.0.1:8000/?healthcheck=1 || exit 1
      interval: ${FOLIOBLOG_HEALTHCHECK_INTERVAL:-60s}
      retries: ${FOLIOBLOG_HEALTHCHECK_RETRIES:-3}

volumes:
  folioblog_media:
    name: folioblog_media
  folioblog_static:
    name: folioblog_static

secrets:
  secret_key:
    environment: FOLIOBLOG_SECRET_KEY
  email_passwd:
    environment: FOLIOBLOG_EMAIL_HOST_PASSWORD
