# Generated by Django 4.1.3 on 2022-11-30 13:44

from django.db import migrations
from wagtail.models import BootstrapTranslatableModel


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_dummytranslatable'),
    ]

    operations = [
        BootstrapTranslatableModel('blog.BlogCategory'),
        BootstrapTranslatableModel('blog.BlogPromote'),
    ]
