# Generated by Django 4.1.3 on 2022-11-30 18:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('blog', '0004_translatable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogindexpage',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='image_alt',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
