# Generated by Django 4.2.6 on 2023-11-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("blog", "0005_image_alt"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="blogcategory",
            unique_together={("translation_key", "locale")},
        ),
        migrations.AddField(
            model_name="blogcategory",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                related_query_name="%(app_label)s_%(class)ss",
                to="wagtailcore.site",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogpromote",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                related_query_name="%(app_label)s_%(class)ss",
                to="wagtailcore.site",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="blogtag",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                related_query_name="%(app_label)s_%(class)ss",
                to="wagtailcore.site",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="blogcategory",
            unique_together={("locale", "slug", "site"), ("translation_key", "locale")},
        ),
    ]
