# Generated by Django 4.2.7 on 2023-11-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("blog", "0006_alter_blogcategory_unique_together_blogcategory_site_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpagerelatedlink",
            name="related_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blog_related_pages",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="blogpromotelink",
            name="related_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoted_links",
                to="blog.blogpage",
            ),
        ),
    ]
