# Generated by Django 4.2.7 on 2023-11-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_alter_blogpagerelatedlink_related_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="author",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
