# Generated by Django 4.2.7 on 2023-11-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("video", "0006_alter_videocategory_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videopagerelatedlink",
            name="related_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="video_related_pages",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="videopromotelink",
            name="related_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="promoted_links",
                to="video.videopage",
            ),
        ),
    ]
