# Generated by Django 4.2.7 on 2023-11-21 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0007_alter_videopagerelatedlink_related_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="videopage",
            name="author",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
