# Generated by Django 4.2.7 on 2023-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("video", "0008_videopage_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="videopage",
            name="date",
            field=models.DateField(verbose_name="Publish date"),
        ),
    ]
