# Generated by Django 4.1.3 on 2022-11-10 15:55

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('core', '0001_initial'),
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('header_heading', models.CharField(default='', max_length=128, verbose_name='Titre')),
                ('header_lead', models.CharField(blank=True, default='', max_length=255, verbose_name='Slogan')),
                ('service_subheading', models.CharField(blank=True, default='', max_length=255, verbose_name='Sous-titre')),
                ('services', wagtail.fields.StreamField([('service', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock(max_length=128)), ('text', wagtail.blocks.TextBlock(required=False)), ('items', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock(icon='list-ul', max_length=128, required=False))), ('icon', wagtail.blocks.CharBlock(max_length=128))]))], blank=True, null=True, use_json_field=True)),
                ('skill_subheading', models.CharField(blank=True, default='', max_length=512, verbose_name='Sous-titre')),
                ('skills', wagtail.fields.StreamField([('skill', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(max_length=128)), ('subheading', wagtail.blocks.CharBlock(max_length=256)), ('intro', wagtail.blocks.CharBlock(max_length=512)), ('text', wagtail.blocks.RichTextBlock()), ('links', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=128)), ('caption', wagtail.blocks.CharBlock(max_length=128, required=False)), ('page', wagtail.blocks.PageChooserBlock(label='Page', required=False)), ('external_url', wagtail.blocks.URLBlock(required=False))]), collapsed=True)), ('image', wagtail.images.blocks.ImageChooserBlock())]))], blank=True, null=True, use_json_field=True)),
                ('about_heading', models.CharField(default='', max_length=128, verbose_name='Titre')),
                ('about_subheading', models.CharField(blank=True, default='', max_length=128, verbose_name='Sous-titre')),
                ('about_text', wagtail.fields.RichTextField(blank=True)),
                ('cv_heading', models.CharField(default='', max_length=128, verbose_name='Titre')),
                ('cv_subheading', models.CharField(blank=True, default='', max_length=128, verbose_name='Sous-titre')),
                ('cv_experiences', wagtail.fields.StreamField([('experience', wagtail.blocks.StructBlock([('date', wagtail.blocks.CharBlock(required=False)), ('company', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.RichTextBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock(required=False))]))], blank=True, null=True, use_json_field=True)),
                ('team_heading', models.CharField(default='', max_length=128, verbose_name='Titre')),
                ('team_subheading', models.CharField(blank=True, default='', max_length=128, verbose_name='Sous-titre')),
                ('team_text', models.CharField(blank=True, default='', max_length=512, verbose_name='Texte')),
                ('team_members', wagtail.fields.StreamField([('member', wagtail.blocks.StructBlock([('name', wagtail.blocks.CharBlock()), ('job', wagtail.blocks.CharBlock()), ('photo', wagtail.images.blocks.ImageChooserBlock()), ('photo_alt', wagtail.blocks.CharBlock())]))], blank=True, null=True, use_json_field=True)),
                ('contact_heading', models.CharField(default='', max_length=128, verbose_name='Titre')),
                ('contact_subheading', models.CharField(blank=True, default='', max_length=128, verbose_name='Sous-titre')),
                ('about_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='portfolio', to='video.videopage')),
                ('header_slide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='core.folioimage', verbose_name='Slide')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
