# Generated by Django 4.2.6 on 2023-10-25 10:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfoliopage",
            name="team_active",
            field=models.BooleanField(default=True),
        ),
    ]
