# Generated by Django 4.2.7 on 2023-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_portfoliopage_team_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="portfoliopage",
            name="about_heading",
            field=models.CharField(default="", max_length=128, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="about_subheading",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="contact_heading",
            field=models.CharField(default="", max_length=128, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="contact_subheading",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="cv_heading",
            field=models.CharField(default="", max_length=128, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="cv_subheading",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="header_heading",
            field=models.CharField(default="", max_length=128, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="service_subheading",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="skill_subheading",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="team_heading",
            field=models.CharField(default="", max_length=128, verbose_name="Title"),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="team_subheading",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Subtitle"
            ),
        ),
        migrations.AlterField(
            model_name="portfoliopage",
            name="team_text",
            field=models.CharField(
                blank=True, default="", max_length=512, verbose_name="Text"
            ),
        ),
    ]
