# Generated by Django 4.1.4 on 2022-12-09 17:13

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='cookie_banner_button_accept_text',
        ),
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='cookie_banner_button_cancel_text',
        ),
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='cookie_banner_link_page',
        ),
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='cookie_banner_link_text',
        ),
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='cookie_banner_text',
        ),
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='cookie_banner_title',
        ),
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='rss_description',
        ),
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='rss_limit',
        ),
        migrations.RemoveField(
            model_name='folioblogsettings',
            name='rss_title',
        ),
        migrations.AddField(
            model_name='folioblogsettings',
            name='cookie_banner',
            field=wagtail.fields.StreamField([('banners', wagtail.blocks.StructBlock([('language', wagtail.blocks.ChoiceBlock(choices=[('en', 'English'), ('fr', 'French')])), ('title', wagtail.blocks.CharBlock(max_length=255)), ('text', wagtail.blocks.TextBlock()), ('page', wagtail.blocks.PageChooserBlock()), ('link_text', wagtail.blocks.CharBlock(max_length=255, required=False)), ('button_cancel_text', wagtail.blocks.CharBlock(max_length=255)), ('button_accept_text', wagtail.blocks.CharBlock(max_length=255))]))], blank=True, null=True, use_json_field=True),
        ),
        migrations.AddField(
            model_name='folioblogsettings',
            name='rss_feed',
            field=wagtail.fields.StreamField([('feeds', wagtail.blocks.StructBlock([('language', wagtail.blocks.ChoiceBlock(choices=[('en', 'English'), ('fr', 'French')])), ('title', wagtail.blocks.CharBlock(max_length=255)), ('description', wagtail.blocks.TextBlock(required=False)), ('limit', wagtail.blocks.IntegerBlock(default=15))]))], blank=True, null=True, use_json_field=True),
        ),
    ]
