# Generated by Django 4.1.4 on 2022-12-12 11:08

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0078_referenceindex'),
        ('core', '0007_folioblogsettings_cookie_rss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='homepage',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='menu_home', to='wagtailcore.page'),
        ),
    ]
