# Generated by Django 4.2.6 on 2023-10-25 09:33

from django.db import migrations, models
import wagtail.images.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_menu_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="folioimage",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                upload_to=wagtail.images.models.get_upload_to,
                verbose_name="file",
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="foliorendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
