# Generated by Django 4.2.6 on 2023-10-25 10:54

from django.db import migrations, models
import wagtail.blocks
import wagtail.fields
import wagtail.images.models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_menu_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="folioblogsettings",
            name="cookie_banner",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banners",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "language",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("en", "English"), ("fr", "French")]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                                (
                                    "button_cancel_text",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                                (
                                    "button_accept_text",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="folioimage",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                upload_to=wagtail.images.models.get_upload_to,
                verbose_name="file",
                width_field="width",
            ),
        ),
        migrations.AlterField(
            model_name="foliorendition",
            name="file",
            field=wagtail.images.models.WagtailImageField(
                height_field="height",
                storage=wagtail.images.models.get_rendition_storage,
                upload_to=wagtail.images.models.get_rendition_upload_to,
                width_field="width",
            ),
        ),
    ]
