# Generated by Django 4.2.6 on 2023-10-25 11:36

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_menu_is_active_alter_folioimage_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folioblogsettings",
            name="cookie_banner",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banners",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "language",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[("en", "English"), ("fr", "French")]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                                (
                                    "button_cancel_text",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                                (
                                    "button_accept_text",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
