# Generated by Django 4.2.6 on 2023-10-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("core", "0010_alter_folioblogsettings_cookie_banner"),
    ]

    operations = [
        migrations.AddField(
            model_name="folioblogsettings",
            name="gallery_collection",
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="wagtailcore.collection",
            ),
        ),
        migrations.AddField(
            model_name="folioblogsettings",
            name="site",
            field=models.OneToOneField(
                default=1,
                editable=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="wagtailcore.site",
            ),
            preserve_default=False,
        ),
    ]
