# Generated by Django 4.2.6 on 2023-11-04 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("core", "0011_folioblogsettings_gallery_collection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                related_query_name="%(app_label)s_%(class)ss",
                to="wagtailcore.site",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="photographer",
            name="site",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s",
                related_query_name="%(app_label)s_%(class)ss",
                to="wagtailcore.site",
            ),
            preserve_default=False,
        ),
    ]
