# Generated by Django 4.2.7 on 2023-11-08 21:00

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_menu_site_photographer_site"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folioblogsettings",
            name="cookie_banner",
            field=wagtail.fields.StreamField(
                [
                    (
                        "banners",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "language",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("en", "English"),
                                            ("fr", "French"),
                                            ("es", "Spanish"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                                ("text", wagtail.blocks.TextBlock()),
                                (
                                    "page",
                                    wagtail.blocks.PageChooserBlock(required=False),
                                ),
                                (
                                    "link_text",
                                    wagtail.blocks.CharBlock(
                                        max_length=255, required=False
                                    ),
                                ),
                                (
                                    "button_cancel_text",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                                (
                                    "button_accept_text",
                                    wagtail.blocks.CharBlock(max_length=255),
                                ),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="folioblogsettings",
            name="rss_feed",
            field=wagtail.fields.StreamField(
                [
                    (
                        "feeds",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "language",
                                    wagtail.blocks.ChoiceBlock(
                                        choices=[
                                            ("en", "English"),
                                            ("fr", "French"),
                                            ("es", "Spanish"),
                                        ]
                                    ),
                                ),
                                ("title", wagtail.blocks.CharBlock(max_length=255)),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(required=False),
                                ),
                                ("limit", wagtail.blocks.IntegerBlock(default=15)),
                            ]
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
            ),
        ),
    ]
