# Generated by Django 4.2.7 on 2023-11-20 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("core", "0013_alter_folioblogsettings_cookie_banner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="basicpagerelatedlink",
            name="related_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="basic_related_pages",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="menu",
            name="homepage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="menu_home",
                to="wagtailcore.page",
            ),
        ),
        migrations.AlterField(
            model_name="menulink",
            name="related_page",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_link",
                to="wagtailcore.page",
            ),
        ),
    ]
