# Generated by Django 4.2.7 on 2023-11-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_alter_basicpagerelatedlink_related_page_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folioblogsettings",
            name="favicon",
            field=models.ImageField(blank=True, default="", upload_to="favicons"),
        ),
    ]
