# Generated by Django 4.2.7 on 2023-11-27 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0016_folioblogsettings_image_404_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="folioblogsettings",
            name="author",
            field=models.CharField(
                blank=True, default="", max_length=128, verbose_name="Meta author"
            ),
        ),
        migrations.AddField(
            model_name="folioblogsettings",
            name="image_password",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folioblogsettings_pwd",
                to="core.folioimage",
                verbose_name="Image password",
            ),
        ),
    ]
