# Generated by Django 4.2.7 on 2023-11-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0089_log_entry_data_json_null_to_object"),
        ("core", "0017_folioblogsettings_author_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menu",
            name="promopage",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="menu_promo",
                to="wagtailcore.page",
            ),
        ),
    ]
