# Generated by Django 4.2.7 on 2023-11-27 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_menu_promopage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="folioblogsettings",
            name="email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="Adresse email utilisé Email address used for contact form submission.",
                max_length=254,
            ),
        ),
    ]
