name: Version

on:
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  version:
    name: version
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Make wagtail version badge
        uses: action-badges/poetry-badges@0.2.2
        with:
          file-name: poetry-wagtail-version.svg
          badge-branch: badges
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          integration: dependency-version
          dependency-type: dependencies
          dependency: wagtail
